[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = true
git_release_enable = true
git_tag_enable = true
publish_allow_dirty = false
release_always = false
semver_check = false

[[package]]
name = "atlas-cli"
publish = false
