//! Session bridge artifacts for fallback event transport.
//!
//! When an adapter cannot write to the session store directly (e.g. the
//! SQLite DB is locked, the process is a short-lived subprocess, or the
//! host lacks a native session-start hook), it writes a markdown bridge file
//! to `.atlas/bridge/` instead.
//!
//! On the next run the adapter ingests pending bridge files:
//! 1. Parse events from the bridge file.
//! 2. Append each event to the session store (best-effort).
//! 3. Index the bridge file content in the content store for retrieval.
//! 4. Remove the consumed file.
//!
//! Stale bridge files (older than `max_age_secs`) are cleaned up even if
//! they could not be fully ingested, so the bridge directory never grows
//! without bound.
//!
//! # Design constraints
//! - Bridge files are never indexed if they contain raw secrets (caller is
//!   responsible for redacting before calling `write_bridge_file`).
//! - Ingest failures are best-effort; a partially-ingested file is deleted
//!   to avoid endless retry loops.
//! - Bridge files must not block primary command execution.

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use serde_json::Value;
use tracing::warn;

use atlas_contentstore::{ContentStore, SourceMeta};
use atlas_session::{NewSessionEvent, SessionEventType, SessionId, SessionStore};

use crate::artifacts::{ArtifactIdentity, generate_source_id};
use crate::redact::redact_payload;

// ── Constants ───────────────────────────────────────────────────────────────

/// Subdirectory inside `.atlas/` where bridge files are written.
pub const BRIDGE_DIR: &str = "bridge";
/// Default maximum age (seconds) before a bridge file is treated as stale.
pub const DEFAULT_BRIDGE_MAX_AGE_SECS: u64 = 86_400; // 24 h

// ── Bridge file schema ──────────────────────────────────────────────────────

/// A single event stored inside a bridge file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BridgeEvent {
    pub event_type: String,
    pub priority: i32,
    /// JSON-encoded payload (already redacted).
    pub payload_json: String,
    /// ISO 8601 timestamp when the event was originally recorded.
    pub created_at: String,
}

/// Envelope written to a bridge file.
#[derive(Debug, Serialize, Deserialize)]
struct BridgeEnvelope {
    schema: String,
    session_id: String,
    frontend: String,
    created_at: String,
    events: Vec<BridgeEvent>,
}

// ── Writing ─────────────────────────────────────────────────────────────────

/// Write `events` to a new bridge file under `bridge_dir`.
///
/// The file is named `bridge-{unix_nanos}.md` so filenames are sortable and
/// unique within a single process.  Payload values are redacted before the
/// file is written so raw secrets never reach disk.
///
/// Returns the path of the created file.
pub fn write_bridge_file(
    bridge_dir: &Path,
    session_id: &SessionId,
    frontend: &str,
    events: &[BridgeEvent],
) -> std::io::Result<PathBuf> {
    std::fs::create_dir_all(bridge_dir)?;

    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let filename = format!("bridge-{ts}.md");
    let path = bridge_dir.join(&filename);

    let now_str = format_now_rfc3339();

    // Redact payloads before writing.
    let redacted_events: Vec<BridgeEvent> = events
        .iter()
        .map(|e| {
            let raw: Value =
                serde_json::from_str(&e.payload_json).unwrap_or(Value::Object(Default::default()));
            let clean = redact_payload(raw);
            BridgeEvent {
                payload_json: serde_json::to_string(&clean).unwrap_or_default(),
                ..e.clone()
            }
        })
        .collect();

    let envelope = BridgeEnvelope {
        schema: "atlas-bridge-v1".to_string(),
        session_id: session_id.as_str().to_string(),
        frontend: frontend.to_string(),
        created_at: now_str.clone(),
        events: redacted_events,
    };

    let json_block = serde_json::to_string_pretty(&envelope)
        .map_err(|e| std::io::Error::other(e.to_string()))?;

    let content = format!(
        "# Atlas Session Bridge\n\n\
         > Generated by Atlas when direct hook payload transport was unavailable.\n\
         > session_id: {sid}  frontend: {fe}  created_at: {ts_str}\n\n\
         ```json\n{json}\n```\n",
        sid = session_id.as_str(),
        fe = frontend,
        ts_str = now_str,
        json = json_block,
    );

    std::fs::write(&path, content)?;
    Ok(path)
}

// ── Listing ─────────────────────────────────────────────────────────────────

/// Return all `.md` bridge file paths in `bridge_dir`, oldest first.
pub fn list_bridge_files(bridge_dir: &Path) -> Vec<PathBuf> {
    let Ok(rd) = std::fs::read_dir(bridge_dir) else {
        return Vec::new();
    };

    let mut paths: Vec<PathBuf> = rd
        .flatten()
        .filter_map(|entry| {
            let p = entry.path();
            if p.extension().is_some_and(|e| e == "md") {
                Some(p)
            } else {
                None
            }
        })
        .collect();

    // Sort by filename (includes timestamp) so ingestion is ordered.
    paths.sort();
    paths
}

/// Return the number of pending bridge files in `bridge_dir`.
pub fn bridge_file_count(bridge_dir: &Path) -> usize {
    list_bridge_files(bridge_dir).len()
}

// ── Ingestion ────────────────────────────────────────────────────────────────

/// Parse a bridge file, append its events to `session_store`, index its
/// markdown content in `content_store`, then delete the file.
///
/// Returns `Ok(n)` where `n` is the number of events appended.  Failures
/// at any step are logged; the file is removed regardless to avoid retrying
/// broken files.
pub fn ingest_bridge_file(
    path: &Path,
    session_store: &mut SessionStore,
    content_store: &mut ContentStore,
) -> usize {
    let raw = match std::fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) => {
            warn!(path = %path.display(), err = %e, "bridge: cannot read file");
            let _ = std::fs::remove_file(path);
            return 0;
        }
    };

    let envelope = match parse_bridge_envelope(&raw) {
        Some(e) => e,
        None => {
            warn!(path = %path.display(), "bridge: cannot parse envelope; discarding");
            let _ = std::fs::remove_file(path);
            return 0;
        }
    };

    let session_id = SessionId(envelope.session_id.clone());

    // Ensure session meta exists (best-effort).
    let _ = session_store.upsert_session_meta(session_id.clone(), "", &envelope.frontend, None);

    let mut appended = 0usize;
    for ev in &envelope.events {
        let Ok(event_type) = ev.event_type.parse::<SessionEventType>() else {
            warn!(event_type = %ev.event_type, "bridge: unknown event type; skipping");
            continue;
        };
        let payload: Value =
            serde_json::from_str(&ev.payload_json).unwrap_or(Value::Object(Default::default()));

        // Payloads were already redacted at write time; no need to re-redact.
        let new_event = NewSessionEvent {
            session_id: session_id.clone(),
            event_type,
            priority: ev.priority,
            payload,
            created_at: Some(ev.created_at.clone()),
        };

        match session_store.append_event(new_event) {
            Ok(_) => appended += 1,
            Err(e) => {
                warn!(err = %e, "bridge: session event append failed (best-effort)");
            }
        }
    }

    // Index the bridge markdown in the content store for retrieval.
    let bridge_identity = ArtifactIdentity::synthetic_path(path.to_string_lossy().into_owned());
    let source_id = generate_source_id(&bridge_identity, &raw);
    let meta = SourceMeta {
        id: source_id,
        session_id: Some(envelope.session_id.clone()),
        agent_id: None,
        source_type: "bridge_artifact".to_string(),
        label: format!(
            "bridge: {} events from {} at {}",
            envelope.events.len(),
            envelope.frontend,
            envelope.created_at,
        ),
        repo_root: None,
        identity_kind: bridge_identity.kind_str().to_owned(),
        identity_value: bridge_identity.value().to_owned(),
    };

    if let Err(e) = content_store.route_output(meta, &raw, "text/markdown") {
        warn!(err = %e, "bridge: content store index failed (best-effort)");
    }

    // Delete the consumed file regardless of index success.
    if let Err(e) = std::fs::remove_file(path) {
        warn!(path = %path.display(), err = %e, "bridge: cannot remove consumed file");
    }

    appended
}

/// Ingest all pending bridge files from `bridge_dir`.
///
/// Returns the total number of events appended across all files.
pub fn ingest_pending_bridge_files(
    bridge_dir: &Path,
    session_store: &mut SessionStore,
    content_store: &mut ContentStore,
) -> usize {
    let files = list_bridge_files(bridge_dir);
    let mut total = 0;
    for path in files {
        total += ingest_bridge_file(&path, session_store, content_store);
    }
    total
}

// ── Cleanup ──────────────────────────────────────────────────────────────────

/// Delete bridge files older than `max_age_secs` seconds, whether consumed
/// or not.  Returns the number of files removed.
pub fn cleanup_stale_bridge_files(bridge_dir: &Path, max_age_secs: u64) -> usize {
    let files = list_bridge_files(bridge_dir);
    let now_secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let mut removed = 0;
    for path in files {
        let mtime = path
            .metadata()
            .ok()
            .and_then(|m| m.modified().ok())
            .and_then(|mt| mt.duration_since(UNIX_EPOCH).ok())
            .map(|d| d.as_secs())
            .unwrap_or(0);

        if now_secs.saturating_sub(mtime) >= max_age_secs {
            match std::fs::remove_file(&path) {
                Ok(_) => removed += 1,
                Err(e) => {
                    warn!(path = %path.display(), err = %e, "bridge: stale file removal failed");
                }
            }
        }
    }
    removed
}

/// Delete all bridge files in `bridge_dir`, returning the count removed.
pub fn purge_all_bridge_files(bridge_dir: &Path) -> usize {
    let files = list_bridge_files(bridge_dir);
    let count = files.len();
    for path in files {
        if let Err(e) = std::fs::remove_file(&path) {
            warn!(path = %path.display(), err = %e, "bridge: purge remove failed");
        }
    }
    count
}

// ── Private helpers ──────────────────────────────────────────────────────────

/// Parse a `BridgeEnvelope` from the JSON block embedded in a bridge markdown file.
fn parse_bridge_envelope(markdown: &str) -> Option<BridgeEnvelope> {
    // Extract the first ```json ... ``` block.
    let start = markdown.find("```json\n")?;
    let after = start + "```json\n".len();
    let end = markdown[after..].find("\n```")?;
    let json_str = &markdown[after..after + end];
    serde_json::from_str(json_str).ok()
}

fn format_now_rfc3339() -> String {
    use std::time::SystemTime;
    let d = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    let secs = d.as_secs();
    // Simple ISO 8601 UTC format without external chrono/time dependency.
    let s = secs % 60;
    let m = (secs / 60) % 60;
    let h = (secs / 3600) % 24;
    let days = secs / 86_400;
    // Approximate Gregorian date from epoch days.
    let (y, mo, da) = epoch_days_to_ymd(days);
    format!("{y:04}-{mo:02}-{da:02}T{h:02}:{m:02}:{s:02}Z")
}

/// Very simple epoch-days → (year, month, day) for ISO formatting.
fn epoch_days_to_ymd(mut days: u64) -> (u64, u64, u64) {
    days += 719_468; // days from 0000-03-01 to 1970-01-01
    let era = days / 146_097;
    let doe = days % 146_097;
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let da = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if mo <= 2 { y + 1 } else { y };
    (y, mo, da)
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_session_id() -> SessionId {
        SessionId::derive(".", "", "cli")
    }

    // ── Write / list ────────────────────────────────────────────────────────

    #[test]
    fn bridge_write_creates_file() {
        let dir = TempDir::new().unwrap();
        let bdir = dir.path().join("bridge");
        let session_id = make_session_id();

        let events = vec![BridgeEvent {
            event_type: "COMMAND_RUN".to_string(),
            priority: 0,
            payload_json: r#"{"command":"atlas build","status":"start"}"#.to_string(),
            created_at: "2024-01-01T00:00:00Z".to_string(),
        }];

        let path = write_bridge_file(&bdir, &session_id, "cli", &events).unwrap();
        assert!(path.exists(), "bridge file must exist after write");
        assert_eq!(path.extension().unwrap(), "md");
    }

    #[test]
    fn bridge_write_redacts_secrets_in_payload() {
        let dir = TempDir::new().unwrap();
        let bdir = dir.path().join("bridge");
        let session_id = make_session_id();

        let events = vec![BridgeEvent {
            event_type: "COMMAND_RUN".to_string(),
            priority: 0,
            payload_json: r#"{"token":"secret-abc","command":"deploy"}"#.to_string(),
            created_at: "2024-01-01T00:00:00Z".to_string(),
        }];

        let path = write_bridge_file(&bdir, &session_id, "cli", &events).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(!content.contains("secret-abc"), "token must be redacted");
    }

    #[test]
    fn bridge_list_returns_sorted_paths() {
        let dir = TempDir::new().unwrap();
        let bdir = dir.path().join("bridge");
        let sid = make_session_id();

        for _ in 0..3 {
            write_bridge_file(&bdir, &sid, "cli", &[]).unwrap();
            // tiny sleep to get distinct nanos on slow systems
            std::thread::sleep(std::time::Duration::from_millis(1));
        }

        let files = list_bridge_files(&bdir);
        assert_eq!(files.len(), 3);
        for w in files.windows(2) {
            assert!(w[0] <= w[1], "files must be sorted");
        }
    }

    #[test]
    fn bridge_count_empty_dir_returns_zero() {
        let dir = TempDir::new().unwrap();
        assert_eq!(bridge_file_count(&dir.path().join("no-such-bridge")), 0);
    }

    // ── Ingest ──────────────────────────────────────────────────────────────

    #[test]
    fn bridge_ingest_appends_events_and_removes_file() {
        let dir = TempDir::new().unwrap();
        std::fs::create_dir_all(dir.path().join(".atlas")).unwrap();
        let bdir = dir.path().join("bridge");
        let sid = SessionId::derive("test-repo", "", "cli");

        let events = vec![
            BridgeEvent {
                event_type: "COMMAND_RUN".to_string(),
                priority: 0,
                payload_json: r#"{"command":"atlas build","status":"start"}"#.to_string(),
                created_at: "2024-01-01T00:00:00Z".to_string(),
            },
            BridgeEvent {
                event_type: "USER_INTENT".to_string(),
                priority: 1,
                payload_json: r#"{"intent":"review PR"}"#.to_string(),
                created_at: "2024-01-01T00:00:01Z".to_string(),
            },
        ];

        let path = write_bridge_file(&bdir, &sid, "cli", &events).unwrap();

        let session_db = dir
            .path()
            .join(".atlas")
            .join("session.db")
            .to_string_lossy()
            .into_owned();
        let content_db = dir
            .path()
            .join(".atlas")
            .join("context.db")
            .to_string_lossy()
            .into_owned();

        let mut ss = SessionStore::open(&session_db).unwrap();
        let mut cs = ContentStore::open(&content_db).unwrap();
        cs.migrate().unwrap();

        let appended = ingest_bridge_file(&path, &mut ss, &mut cs);
        assert_eq!(appended, 2, "both events must be appended");
        assert!(!path.exists(), "bridge file must be removed after ingest");

        let hits = cs
            .search_with_fallback("atlas build", &atlas_contentstore::SearchFilters::default())
            .unwrap();
        let source = cs.get_source(&hits[0].source_id).unwrap().unwrap();
        assert_eq!(source.identity_kind, "synthetic_path");
        assert!(source.identity_value.contains("bridge-"));
    }

    #[test]
    fn bridge_ingest_discards_unreadable_file() {
        let dir = TempDir::new().unwrap();
        let nonexistent = dir.path().join("ghost.md");
        let session_db = dir.path().join("session.db").to_string_lossy().into_owned();
        let content_db = dir.path().join("context.db").to_string_lossy().into_owned();
        let mut ss = SessionStore::open(&session_db).unwrap();
        let mut cs = ContentStore::open(&content_db).unwrap();
        cs.migrate().unwrap();

        let count = ingest_bridge_file(&nonexistent, &mut ss, &mut cs);
        assert_eq!(count, 0);
    }

    #[test]
    fn bridge_ingest_pending_returns_total_events() {
        let dir = TempDir::new().unwrap();
        std::fs::create_dir_all(dir.path().join(".atlas")).unwrap();
        let bdir = dir.path().join("bridge");
        let sid = SessionId::derive("repo", "", "mcp");

        let one_event = vec![BridgeEvent {
            event_type: "COMMAND_RUN".to_string(),
            priority: 0,
            payload_json: r#"{"command":"atlas update"}"#.to_string(),
            created_at: "2024-01-01T00:00:00Z".to_string(),
        }];

        write_bridge_file(&bdir, &sid, "mcp", &one_event).unwrap();
        write_bridge_file(&bdir, &sid, "mcp", &one_event).unwrap();

        let session_db = dir
            .path()
            .join(".atlas")
            .join("session.db")
            .to_string_lossy()
            .into_owned();
        let content_db = dir
            .path()
            .join(".atlas")
            .join("context.db")
            .to_string_lossy()
            .into_owned();

        let mut ss = SessionStore::open(&session_db).unwrap();
        let mut cs = ContentStore::open(&content_db).unwrap();
        cs.migrate().unwrap();

        let total = ingest_pending_bridge_files(&bdir, &mut ss, &mut cs);
        // 2 files × 1 event each, but second is a dedup of the first
        assert!(total <= 2, "must not exceed 2");
        assert_eq!(list_bridge_files(&bdir).len(), 0, "all files consumed");
    }

    // ── Cleanup / purge ─────────────────────────────────────────────────────

    #[test]
    fn bridge_cleanup_removes_stale_files() {
        let dir = TempDir::new().unwrap();
        let bdir = dir.path().join("bridge");
        let sid = make_session_id();

        let path = write_bridge_file(&bdir, &sid, "cli", &[]).unwrap();

        // max_age_secs = 0 means any file is considered stale immediately.
        let removed = cleanup_stale_bridge_files(&bdir, 0);
        assert_eq!(removed, 1);
        assert!(!path.exists());
    }

    #[test]
    fn bridge_cleanup_keeps_recent_files() {
        let dir = TempDir::new().unwrap();
        let bdir = dir.path().join("bridge");
        let sid = make_session_id();

        write_bridge_file(&bdir, &sid, "cli", &[]).unwrap();
        let removed = cleanup_stale_bridge_files(&bdir, DEFAULT_BRIDGE_MAX_AGE_SECS);
        assert_eq!(removed, 0, "recent files must not be purged");
        assert_eq!(bridge_file_count(&bdir), 1);
    }

    #[test]
    fn bridge_purge_all_removes_everything() {
        let dir = TempDir::new().unwrap();
        let bdir = dir.path().join("bridge");
        let sid = make_session_id();

        write_bridge_file(&bdir, &sid, "cli", &[]).unwrap();
        write_bridge_file(&bdir, &sid, "cli", &[]).unwrap();
        let removed = purge_all_bridge_files(&bdir);
        assert_eq!(removed, 2);
        assert_eq!(bridge_file_count(&bdir), 0);
    }

    // ── Parse round-trip ────────────────────────────────────────────────────

    #[test]
    fn bridge_parse_envelope_round_trips() {
        let dir = TempDir::new().unwrap();
        let bdir = dir.path().join("bridge");
        let sid = make_session_id();

        let events = vec![BridgeEvent {
            event_type: "USER_INTENT".to_string(),
            priority: 2,
            payload_json: r#"{"intent":"test round-trip"}"#.to_string(),
            created_at: "2024-06-01T10:00:00Z".to_string(),
        }];

        let path = write_bridge_file(&bdir, &sid, "mcp", &events).unwrap();
        let raw = std::fs::read_to_string(&path).unwrap();
        let envelope = parse_bridge_envelope(&raw).expect("must parse");

        assert_eq!(envelope.schema, "atlas-bridge-v1");
        assert_eq!(envelope.session_id, sid.as_str());
        assert_eq!(envelope.frontend, "mcp");
        assert_eq!(envelope.events.len(), 1);
        assert_eq!(envelope.events[0].event_type, "USER_INTENT");
    }
}
